#!/usr/bin/env bash
# an algo of scripti that pings an andress ip

ip="${1}"


file_name=$(basename "${BASH_SOURCE[@]}")

if ! [ "$ip" ]; then
	echo "Usage: ${file_name} {IP_ADDRESS}"
else
	ping -c 5 "${ip}"
fi
