#!/usr/bin/env bash
# Configuration of ngnix server

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo pkill nginx
sudo service nginx start
